for user in nathandrake donkeykong laracroft bowser; do
    useradd -m -s /bin/bash $user
    echo "$user:12345678" | chpasswd
done

mkdir -p /srv/skoda/documents
mkdir -p /srv/skoda/backup

chown nobody:nogroup /srv/skoda/documents
chmod 755 /srv/skoda/documents

chgrp users /srv/skoda/documents /srv/skoda/backup
chmod 775 /srv/skoda/documents /srv/skoda/backup
usermod -aG users laracroft
usermod -aG users bowser


nano /etc/vsftpd.conf

# Configuración Básica
listen=NO
listen_ipv6=YES
anonymous_enable=YES
local_enable=YES
write_enable=YES
local_umask=022

chroot_local_user=YES
allow_writeable_chroot=YES

chroot_list_enable=YES
chroot_list_file=/etc/vsftpd.chroot_list

anon_root=/srv/skoda/documents
no_anon_password=YES
hide_ids=YES

Crea el archivo de excepciones:
nano /etc/vsftpd.chroot_list

Y añade los nombres de los usuarios que no estarán engabiados:
laracroft
bowser


ln -s /srv/skoda/documents /home/laracroft/documents
ln -s /srv/skoda/backup /home/laracroft/backup
ln -s /srv/skoda/documents /home/bowser/documents
ln -s /srv/skoda/backup /home/bowser/backup


systemctl restart vsftpd
